main: net.tfminecraft.gunsandgadgets.GunsAndGadgets
api-version: '1.21.10'
name: GunsAndGadgets
version: ${project.version}
author: Drefvelin

depend: [TLibs, MythicLib, MMOItems, MMOCore]

commands:
  gg:
    description: GunsAndGadgets admin commands
    usage: /<command> reload|refresh
    permission: gunsandgadgets.reload
    permission-message: You do not have permission to use GunsAndGadgets admin commands.

permissions:
  gunsandgadgets.reload:
    description: Reload GunsAndGadgets configs (skins, parts, ammunition, config)
    default: op
